//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 04:41:50 PM CET 
//


package model.ws.es;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import model.ws.AbstractWsObject;


/**
 * <p>Java class for configuration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configuration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="documentConfigurationParams" type="{http://service.search.portal.products.expertsystem.net/}configurationParams" minOccurs="0"/>
 *         &lt;element name="faqcConfigurationParams" type="{http://service.search.portal.products.expertsystem.net/}configurationParams" minOccurs="0"/>
 *         &lt;element name="faqsConfigurationParams" type="{http://service.search.portal.products.expertsystem.net/}configurationParams" minOccurs="0"/>
 *         &lt;element name="slinkConfigurationParams" type="{http://service.search.portal.products.expertsystem.net/}configurationParams" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configuration", namespace = "http://service.search.portal.products.expertsystem.net/", propOrder = {
    "documentConfigurationParams",
    "faqcConfigurationParams",
    "faqsConfigurationParams",
    "slinkConfigurationParams"
})
public class Configuration
    extends AbstractWsObject
{

    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected ConfigurationParams documentConfigurationParams;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected ConfigurationParams faqcConfigurationParams;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected ConfigurationParams faqsConfigurationParams;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected ConfigurationParams slinkConfigurationParams;

    /**
     * Gets the value of the documentConfigurationParams property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationParams }
     *     
     */
    public ConfigurationParams getDocumentConfigurationParams() {
        return documentConfigurationParams;
    }

    /**
     * Sets the value of the documentConfigurationParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationParams }
     *     
     */
    public void setDocumentConfigurationParams(ConfigurationParams value) {
        this.documentConfigurationParams = value;
    }

    /**
     * Gets the value of the faqcConfigurationParams property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationParams }
     *     
     */
    public ConfigurationParams getFaqcConfigurationParams() {
        return faqcConfigurationParams;
    }

    /**
     * Sets the value of the faqcConfigurationParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationParams }
     *     
     */
    public void setFaqcConfigurationParams(ConfigurationParams value) {
        this.faqcConfigurationParams = value;
    }

    /**
     * Gets the value of the faqsConfigurationParams property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationParams }
     *     
     */
    public ConfigurationParams getFaqsConfigurationParams() {
        return faqsConfigurationParams;
    }

    /**
     * Sets the value of the faqsConfigurationParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationParams }
     *     
     */
    public void setFaqsConfigurationParams(ConfigurationParams value) {
        this.faqsConfigurationParams = value;
    }

    /**
     * Gets the value of the slinkConfigurationParams property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationParams }
     *     
     */
    public ConfigurationParams getSlinkConfigurationParams() {
        return slinkConfigurationParams;
    }

    /**
     * Sets the value of the slinkConfigurationParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationParams }
     *     
     */
    public void setSlinkConfigurationParams(ConfigurationParams value) {
        this.slinkConfigurationParams = value;
    }

}
