//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 04:41:50 PM CET 
//


package model.ws.es;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model.ws.es package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model.ws.es
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Document.MetadataMap }
     * 
     */
    public Document.MetadataMap createDocumentMetadataMap() {
        return new Document.MetadataMap();
    }

    /**
     * Create an instance of {@link ProductSearchQuery }
     * 
     */
    public ProductSearchQuery createProductSearchQuery() {
        return new ProductSearchQuery();
    }

    /**
     * Create an instance of {@link ProductSearchQuery.StatisticsMetavaluesMap }
     * 
     */
    public ProductSearchQuery.StatisticsMetavaluesMap createProductSearchQueryStatisticsMetavaluesMap() {
        return new ProductSearchQuery.StatisticsMetavaluesMap();
    }

    /**
     * Create an instance of {@link SearchResponse }
     * 
     */
    public SearchResponse createSearchResponse() {
        return new SearchResponse();
    }

    /**
     * Create an instance of {@link ProductSearchResult }
     * 
     */
    public ProductSearchResult createProductSearchResult() {
        return new ProductSearchResult();
    }

    /**
     * Create an instance of {@link Search }
     * 
     */
    public Search createSearch() {
        return new Search();
    }

    /**
     * Create an instance of {@link DocumentIdentifier }
     * 
     */
    public DocumentIdentifier createDocumentIdentifier() {
        return new DocumentIdentifier();
    }

    /**
     * Create an instance of {@link Sentence }
     * 
     */
    public Sentence createSentence() {
        return new Sentence();
    }

    /**
     * Create an instance of {@link HashMap }
     * 
     */
    public HashMap createHashMap() {
        return new HashMap();
    }

    /**
     * Create an instance of {@link Highlight }
     * 
     */
    public Highlight createHighlight() {
        return new Highlight();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link SearchResult }
     * 
     */
    public SearchResult createSearchResult() {
        return new SearchResult();
    }

    /**
     * Create an instance of {@link Sao }
     * 
     */
    public Sao createSao() {
        return new Sao();
    }

    /**
     * Create an instance of {@link Values }
     * 
     */
    public Values createValues() {
        return new Values();
    }

    /**
     * Create an instance of {@link FieldValue }
     * 
     */
    public FieldValue createFieldValue() {
        return new FieldValue();
    }

    /**
     * Create an instance of {@link ConfigurationParams }
     * 
     */
    public ConfigurationParams createConfigurationParams() {
        return new ConfigurationParams();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link FieldValues }
     * 
     */
    public FieldValues createFieldValues() {
        return new FieldValues();
    }

    /**
     * Create an instance of {@link Document.MetadataMap.Entry }
     * 
     */
    public Document.MetadataMap.Entry createDocumentMetadataMapEntry() {
        return new Document.MetadataMap.Entry();
    }

    /**
     * Create an instance of {@link ProductSearchQuery.StatisticsMetavaluesMap.Entry }
     * 
     */
    public ProductSearchQuery.StatisticsMetavaluesMap.Entry createProductSearchQueryStatisticsMetavaluesMapEntry() {
        return new ProductSearchQuery.StatisticsMetavaluesMap.Entry();
    }

}
