//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 04:41:50 PM CET 
//


package model.ws.es;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import model.ws.AbstractWsObject;


/**
 * <p>Java class for productSearchResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productSearchResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="categFaqSearchResult" type="{http://service.search.portal.products.expertsystem.net/}searchResult" minOccurs="0"/>
 *         &lt;element name="didYouMean" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="originalText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rankedSearchResult" type="{http://service.search.portal.products.expertsystem.net/}searchResult" minOccurs="0"/>
 *         &lt;element name="searchId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simpleFaqSearchResult" type="{http://service.search.portal.products.expertsystem.net/}searchResult" minOccurs="0"/>
 *         &lt;element name="sponsoredLinkSearchResult" type="{http://service.search.portal.products.expertsystem.net/}searchResult" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productSearchResult", namespace = "http://service.search.portal.products.expertsystem.net/", propOrder = {
    "categFaqSearchResult",
    "didYouMean",
    "originalText",
    "rankedSearchResult",
    "searchId",
    "simpleFaqSearchResult",
    "sponsoredLinkSearchResult"
})
public class ProductSearchResult
    extends AbstractWsObject
{

    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected SearchResult categFaqSearchResult;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String didYouMean;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String originalText;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected SearchResult rankedSearchResult;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String searchId;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected SearchResult simpleFaqSearchResult;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected SearchResult sponsoredLinkSearchResult;

    /**
     * Gets the value of the categFaqSearchResult property.
     * 
     * @return
     *     possible object is
     *     {@link SearchResult }
     *     
     */
    public SearchResult getCategFaqSearchResult() {
        return categFaqSearchResult;
    }

    /**
     * Sets the value of the categFaqSearchResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchResult }
     *     
     */
    public void setCategFaqSearchResult(SearchResult value) {
        this.categFaqSearchResult = value;
    }

    /**
     * Gets the value of the didYouMean property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDidYouMean() {
        return didYouMean;
    }

    /**
     * Sets the value of the didYouMean property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDidYouMean(String value) {
        this.didYouMean = value;
    }

    /**
     * Gets the value of the originalText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalText() {
        return originalText;
    }

    /**
     * Sets the value of the originalText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalText(String value) {
        this.originalText = value;
    }

    /**
     * Gets the value of the rankedSearchResult property.
     * 
     * @return
     *     possible object is
     *     {@link SearchResult }
     *     
     */
    public SearchResult getRankedSearchResult() {
        return rankedSearchResult;
    }

    /**
     * Sets the value of the rankedSearchResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchResult }
     *     
     */
    public void setRankedSearchResult(SearchResult value) {
        this.rankedSearchResult = value;
    }

    /**
     * Gets the value of the searchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchId() {
        return searchId;
    }

    /**
     * Sets the value of the searchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchId(String value) {
        this.searchId = value;
    }

    /**
     * Gets the value of the simpleFaqSearchResult property.
     * 
     * @return
     *     possible object is
     *     {@link SearchResult }
     *     
     */
    public SearchResult getSimpleFaqSearchResult() {
        return simpleFaqSearchResult;
    }

    /**
     * Sets the value of the simpleFaqSearchResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchResult }
     *     
     */
    public void setSimpleFaqSearchResult(SearchResult value) {
        this.simpleFaqSearchResult = value;
    }

    /**
     * Gets the value of the sponsoredLinkSearchResult property.
     * 
     * @return
     *     possible object is
     *     {@link SearchResult }
     *     
     */
    public SearchResult getSponsoredLinkSearchResult() {
        return sponsoredLinkSearchResult;
    }

    /**
     * Sets the value of the sponsoredLinkSearchResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchResult }
     *     
     */
    public void setSponsoredLinkSearchResult(SearchResult value) {
        this.sponsoredLinkSearchResult = value;
    }

}
