//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 04:41:50 PM CET 
//


package model.ws.es;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import model.ws.AbstractWsObject;


/**
 * <p>Java class for productSearchQuery complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productSearchQuery">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="areaSiteId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="assetProdIds" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="assetServIds" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="clientType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="configuration" type="{http://service.search.portal.products.expertsystem.net/}configuration" minOccurs="0"/>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="expressionFilter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flagDidYouMean" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="generateStats" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="pageNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pageSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="projectLanguage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="queryLanguage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="siteId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="siteLoginId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sourceId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statisticsMetavaluesMap">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="value" type="{http://service.search.portal.products.expertsystem.net/}values" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="statusProd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subCustomerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="textOld" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="topicId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productSearchQuery", namespace = "http://service.search.portal.products.expertsystem.net/", propOrder = {
    "areaSiteId",
    "assetProdIds",
    "assetServIds",
    "clientType",
    "configuration",
    "customerId",
    "expressionFilter",
    "flagDidYouMean",
    "generateStats",
    "pageNumber",
    "pageSize",
    "productId",
    "projectLanguage",
    "queryLanguage",
    "siteId",
    "siteLoginId",
    "sourceId",
    "statisticsMetavaluesMap",
    "statusProd",
    "subCustomerId",
    "text",
    "textOld",
    "topicId",
    "userName"
})
public class ProductSearchQuery
    extends AbstractWsObject
{

    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String areaSiteId;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/", nillable = true)
    protected List<String> assetProdIds;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/", nillable = true)
    protected List<String> assetServIds;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String clientType;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected Configuration configuration;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String customerId;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String expressionFilter;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected boolean flagDidYouMean;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected boolean generateStats;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected int pageNumber;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected int pageSize;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String productId;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String projectLanguage;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String queryLanguage;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String siteId;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String siteLoginId;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String sourceId;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/", required = true)
    protected ProductSearchQuery.StatisticsMetavaluesMap statisticsMetavaluesMap;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String statusProd;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String subCustomerId;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String text;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String textOld;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String topicId;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String userName;

    /**
     * Gets the value of the areaSiteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaSiteId() {
        return areaSiteId;
    }

    /**
     * Sets the value of the areaSiteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaSiteId(String value) {
        this.areaSiteId = value;
    }

    /**
     * Gets the value of the assetProdIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assetProdIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssetProdIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAssetProdIds() {
        if (assetProdIds == null) {
            assetProdIds = new ArrayList<String>();
        }
        return this.assetProdIds;
    }

    /**
     * Gets the value of the assetServIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assetServIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssetServIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAssetServIds() {
        if (assetServIds == null) {
            assetServIds = new ArrayList<String>();
        }
        return this.assetServIds;
    }

    /**
     * Gets the value of the clientType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * Sets the value of the clientType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientType(String value) {
        this.clientType = value;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration }
     *     
     */
    public Configuration getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration }
     *     
     */
    public void setConfiguration(Configuration value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerId(String value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the expressionFilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpressionFilter() {
        return expressionFilter;
    }

    /**
     * Sets the value of the expressionFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpressionFilter(String value) {
        this.expressionFilter = value;
    }

    /**
     * Gets the value of the flagDidYouMean property.
     * 
     */
    public boolean isFlagDidYouMean() {
        return flagDidYouMean;
    }

    /**
     * Sets the value of the flagDidYouMean property.
     * 
     */
    public void setFlagDidYouMean(boolean value) {
        this.flagDidYouMean = value;
    }

    /**
     * Gets the value of the generateStats property.
     * 
     */
    public boolean isGenerateStats() {
        return generateStats;
    }

    /**
     * Sets the value of the generateStats property.
     * 
     */
    public void setGenerateStats(boolean value) {
        this.generateStats = value;
    }

    /**
     * Gets the value of the pageNumber property.
     * 
     */
    public int getPageNumber() {
        return pageNumber;
    }

    /**
     * Sets the value of the pageNumber property.
     * 
     */
    public void setPageNumber(int value) {
        this.pageNumber = value;
    }

    /**
     * Gets the value of the pageSize property.
     * 
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     * 
     */
    public void setPageSize(int value) {
        this.pageSize = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the projectLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectLanguage() {
        return projectLanguage;
    }

    /**
     * Sets the value of the projectLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectLanguage(String value) {
        this.projectLanguage = value;
    }

    /**
     * Gets the value of the queryLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryLanguage() {
        return queryLanguage;
    }

    /**
     * Sets the value of the queryLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryLanguage(String value) {
        this.queryLanguage = value;
    }

    /**
     * Gets the value of the siteId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * Sets the value of the siteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteId(String value) {
        this.siteId = value;
    }

    /**
     * Gets the value of the siteLoginId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteLoginId() {
        return siteLoginId;
    }

    /**
     * Sets the value of the siteLoginId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteLoginId(String value) {
        this.siteLoginId = value;
    }

    /**
     * Gets the value of the sourceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * Sets the value of the sourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceId(String value) {
        this.sourceId = value;
    }

    /**
     * Gets the value of the statisticsMetavaluesMap property.
     * 
     * @return
     *     possible object is
     *     {@link ProductSearchQuery.StatisticsMetavaluesMap }
     *     
     */
    public ProductSearchQuery.StatisticsMetavaluesMap getStatisticsMetavaluesMap() {
        return statisticsMetavaluesMap;
    }

    /**
     * Sets the value of the statisticsMetavaluesMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductSearchQuery.StatisticsMetavaluesMap }
     *     
     */
    public void setStatisticsMetavaluesMap(ProductSearchQuery.StatisticsMetavaluesMap value) {
        this.statisticsMetavaluesMap = value;
    }

    /**
     * Gets the value of the statusProd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusProd() {
        return statusProd;
    }

    /**
     * Sets the value of the statusProd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusProd(String value) {
        this.statusProd = value;
    }

    /**
     * Gets the value of the subCustomerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCustomerId() {
        return subCustomerId;
    }

    /**
     * Sets the value of the subCustomerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCustomerId(String value) {
        this.subCustomerId = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the textOld property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextOld() {
        return textOld;
    }

    /**
     * Sets the value of the textOld property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextOld(String value) {
        this.textOld = value;
    }

    /**
     * Gets the value of the topicId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopicId() {
        return topicId;
    }

    /**
     * Sets the value of the topicId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopicId(String value) {
        this.topicId = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entry" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="value" type="{http://service.search.portal.products.expertsystem.net/}values" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entry"
    })
    public static class StatisticsMetavaluesMap
        extends AbstractWsObject
    {

        @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
        protected List<ProductSearchQuery.StatisticsMetavaluesMap.Entry> entry;

        /**
         * Gets the value of the entry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProductSearchQuery.StatisticsMetavaluesMap.Entry }
         * 
         * 
         */
        public List<ProductSearchQuery.StatisticsMetavaluesMap.Entry> getEntry() {
            if (entry == null) {
                entry = new ArrayList<ProductSearchQuery.StatisticsMetavaluesMap.Entry>();
            }
            return this.entry;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="value" type="{http://service.search.portal.products.expertsystem.net/}values" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "key",
            "value"
        })
        public static class Entry
            extends AbstractWsObject
        {

            @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
            protected String key;
            @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
            protected Values value;

            /**
             * Gets the value of the key property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKey() {
                return key;
            }

            /**
             * Sets the value of the key property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKey(String value) {
                this.key = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link Values }
             *     
             */
            public Values getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link Values }
             *     
             */
            public void setValue(Values value) {
                this.value = value;
            }

        }

    }

}
