//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 04:41:50 PM CET 
//


package model.ws.es;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import model.ws.AbstractWsObject;


/**
 * <p>Java class for sentence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sentence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fields" type="{http://service.search.portal.products.expertsystem.net/}field" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="firstPropositions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="highlights" type="{http://service.search.portal.products.expertsystem.net/}highlight" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="saos" type="{http://service.search.portal.products.expertsystem.net/}sao" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="secondPropositions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sentenceId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sentence", namespace = "http://service.search.portal.products.expertsystem.net/", propOrder = {
    "fields",
    "firstPropositions",
    "highlights",
    "rank",
    "saos",
    "secondPropositions",
    "sentenceId",
    "text"
})
public class Sentence
    extends AbstractWsObject
{

    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/", nillable = true)
    protected List<Field> fields;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/", nillable = true)
    protected List<String> firstPropositions;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/", nillable = true)
    protected List<Highlight> highlights;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String rank;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/", nillable = true)
    protected List<Sao> saos;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/", nillable = true)
    protected List<String> secondPropositions;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String sentenceId;
    @XmlElement(namespace = "http://service.search.portal.products.expertsystem.net/")
    protected String text;

    /**
     * Gets the value of the fields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFields().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getFields() {
        if (fields == null) {
            fields = new ArrayList<Field>();
        }
        return this.fields;
    }

    /**
     * Gets the value of the firstPropositions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the firstPropositions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFirstPropositions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFirstPropositions() {
        if (firstPropositions == null) {
            firstPropositions = new ArrayList<String>();
        }
        return this.firstPropositions;
    }

    /**
     * Gets the value of the highlights property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the highlights property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHighlights().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Highlight }
     * 
     * 
     */
    public List<Highlight> getHighlights() {
        if (highlights == null) {
            highlights = new ArrayList<Highlight>();
        }
        return this.highlights;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRank(String value) {
        this.rank = value;
    }

    /**
     * Gets the value of the saos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the saos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSaos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sao }
     * 
     * 
     */
    public List<Sao> getSaos() {
        if (saos == null) {
            saos = new ArrayList<Sao>();
        }
        return this.saos;
    }

    /**
     * Gets the value of the secondPropositions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the secondPropositions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecondPropositions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSecondPropositions() {
        if (secondPropositions == null) {
            secondPropositions = new ArrayList<String>();
        }
        return this.secondPropositions;
    }

    /**
     * Gets the value of the sentenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentenceId() {
        return sentenceId;
    }

    /**
     * Sets the value of the sentenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentenceId(String value) {
        this.sentenceId = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

}
